<a href="https://colab.research.google.com/github/simran-sharma29/MSC-IT-PARTII-SEM-3/blob/main/DL/PRACT3/A/DLPRACT3a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Practical 3a**
Aim: Implementing a deep neural network for performing classification task.

In [ ]:

#Problem statement: 
#The given dataset comprises health information about diabetic women patients. We need to create a deep feed forward network that will classify women suffering from diabetes mellitus as 1.
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

dataset=loadtxt('/content/sample_data/pima-indians-diabetes.csv',delimiter=',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
X=dataset[:,0:8]
Y=dataset[:,8]
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [ ]:
#Creating model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#Compiling and fitting model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 43.7715 - accuracy: 0.3490
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 10.4616 - accuracy: 0.3529
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 3.2980 - accuracy: 0.3932
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 1.0124 - accuracy: 0.6328
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8380 - accuracy: 0.6628
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7541 - accuracy: 0.6654
Epoch 7/150
77/77 [==============================] - 0s 1ms/step - loss: 0.7034 - accuracy: 0.6706
Epoch 8/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6750 - accuracy: 0.6693
Epoch 9/150
77/77 [==============================] - 0s 1ms/step - loss: 0.6556 - accuracy: 0.6680
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6416 - accuracy: 0.6771
Epoch 1

In [ ]:
model.fit(X, Y, epochs=150, batch_size=10)


predictions = model.predict(X)

rounded = [round(x[0]) for x in predictions]
print(rounded)


scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))



Epoch 1/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5952 - accuracy: 0.7109
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5889 - accuracy: 0.7083
Epoch 3/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5960 - accuracy: 0.7005
Epoch 4/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5876 - accuracy: 0.7083
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5857 - accuracy: 0.7018
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5879 - accuracy: 0.7057
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5917 - accuracy: 0.7044
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5873 - accuracy: 0.7135
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5857 - accuracy: 0.7057
Epoch 10/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5881 - accuracy: 0.6914
Epoch 11/