<a href="https://colab.research.google.com/github/simran-sharma29/MSC-IT-PARTII-SEM-3/blob/main/DL/PRACT1/DLPRACT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**PRACTICAL 1**

In [ ]:
#Import TensorFlow
import tensorflow as tf


In [ ]:
#create a row vector x containing the first 12 integers starting with 0
x = tf.range(12)
x


<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [ ]:
# A Tensor's shape
x.shape


TensorShape([12])

In [ ]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
# Change the shape of a tensor 
X = tf.reshape(x, (3, 4))
X


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [ ]:
 
# Change the shape of a tensor 
X = tf.reshape(x, (3, 4))
X
 



<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [ ]:
#Create Matrix of Zeros
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Create Matrix of One’s

tf.ones((3,2,2))

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [ ]:
tf.random.normal(shape=[3, 4])


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.6456247 ,  0.77065855,  0.5880463 ,  0.3062835 ],
       [-2.0349705 , -1.580224  , -0.10106778, -0.23893967],
       [-2.064731  , -0.02762979,  1.0740911 ,  0.52167815]],
      dtype=float32)>

In [ ]:
tf.__version__


'2.7.0'

In [ ]:
a=tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
b=tf.constant(3)
b


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

In [ ]:
#Operations
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
print(x + y)

print(x - y)
print(x * y)
print(x / y)
print(x**y)  # The ** operator is exponentiation


tf.Tensor([ 3.  4.  6. 10.], shape=(4,), dtype=float32)
tf.Tensor([-1.  0.  2.  6.], shape=(4,), dtype=float32)
tf.Tensor([ 2.  4.  8. 16.], shape=(4,), dtype=float32)
tf.Tensor([0.5 1.  2.  4. ], shape=(4,), dtype=float32)
tf.Tensor([ 1.  4. 16. 64.], shape=(4,), dtype=float32)


In [ ]:
tf.exp(x)


<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

In [ ]:
#Concatenation
X=tf.constant([[1, 1, 1, 1], [2, 2, 3, 3]])
Y=tf.constant([[3, 3, 3, 3], [4, 4, 4, 4]])
Z=tf.concat([X, Y], axis=0)
Z

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [2, 2, 3, 3],
       [3, 3, 3, 3],
       [4, 4, 4, 4]], dtype=int32)>

In [ ]:
#Concatenation
X=tf.constant([[1, 1, 1, 1], [2, 2, 3, 3]])
Y=tf.constant([[3, 3, 3, 3], [4, 4, 4, 4]])
Z=tf.concat([X, Y], axis=1)  # or axis =1
Z


<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 3, 3, 3, 3],
       [2, 2, 3, 3, 4, 4, 4, 4]], dtype=int32)>

In [ ]:
X==Y   #Check for equality


<tf.Tensor: shape=(2, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False]])>

In [ ]:
tf.reduce_sum(X)
 


<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [ ]:
#Concatenation
X1=tf.constant([[1, 1,1], [2, 2,3]])
Y1=tf.constant([[3, 3], [4, 4], [4, 4]])
X1,Y1



(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 1, 1],
        [2, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 3],
        [4, 4],
        [4, 4]], dtype=int32)>)

In [ ]:
print(X+Y)

tf.Tensor(
[[4 4 4 4]
 [6 6 7 7]], shape=(2, 4), dtype=int32)


In [ ]:
#Variable
v = tf.Variable(1.)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [ ]:
v.assign(2.)
v


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [ ]:
w = tf.Variable([[1.], [2.]])
x = tf.constant([[3., 4.]])
tf.matmul(w, x)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

Practical 1
Aim: Performing matrix multiplication and finding eigen vectors and eigen values using TensorFlow.

In [ ]:
import tensorflow as tf 

In [ ]:
print("Matrix Multiplication Demo") 
x=tf.constant([1,2,3,4,5,6],shape=[2,3]) 
print(x) 

Matrix Multiplication Demo
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
y=tf.constant([7,8,9,10,11,12],shape=[3,2]) 
print(y)

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [ ]:
z=tf.matmul(x,y) 
print("Product:",z) 

Product: tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [ ]:
e_matrix_A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32,name="matrixA") 
 
print("Matrix A:\n{}\n\n".format(e_matrix_A)) 
 

Matrix A:
[[4.158293  4.2793894]
 [9.866041  3.1019793]]




In [ ]:
eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A) 
 
print("Eigen Vectors:\n{}\n\nEigen values:\n{}\n".format(eigen_vectors_A, eigen_values_A))


Eigen Vectors:
[[-0.6879476  0.7257604]
 [ 0.7257604  0.6879476]]

Eigen values:
[-6.2500315 13.510304 ]



Practical 3

Aim: Implementing a deep neural network for performing classification task.
Problem statement: 
The given dataset comprises health information about diabetic women patients. We need to create a deep feed forward network that will classify women suffering from diabetes mellitus as


In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import numpy
import pandas as pd

In [ ]:
dataset = numpy.loadtxt("/content/drive/MyDrive/Colab Notebooks/Data Files/pima-indians-diabetes.csv", delimiter=",")


In [ ]:
X = dataset[:,0:8]
Y = dataset[:,8]


In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
model.fit(X, Y, epochs=150, batch_size=10)


predictions = model.predict(X)

rounded = [round(x[0]) for x in predictions]
print(rounded)






Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 3.6909 - accuracy: 0.6445
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.0838 - accuracy: 0.6211
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9614 - accuracy: 0.6211
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8432 - accuracy: 0.6211
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7718 - accuracy: 0.6510
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7471 - accuracy: 0.6484
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7161 - accuracy: 0.6510
Epoch 8/150
77/77 [==============================] - 0s 1ms/step - loss: 0.7153 - accuracy: 0.6445
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7252 - accuracy: 0.6549
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6773 - accuracy: 0.6471
Epoch 11/

In [ ]:
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

24/24 [==============================] - 0s 1ms/step - loss: 0.6036 - accuracy: 0.6862

accuracy: 68.62%
